### ISSUE TITLE
[US-2] Requesting book information

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#29]
**As Sergio the bookworm from MMR,
I want to request information about books from a database,
so I can know if I am interested in them according to their details.**

---

This will require:

- A data structure representing the books
- A database with examples of books, following the previous structure
- Functionality to retrieve such books and their metadata (and also create instances of them if it was not done before)

### Related personas

[Reader users](https://github.com/Anglepi/My-Many-Reads/tree/main/docs/md/personas/reader-users.md)

### Tasks

#31 #32 #33

### Technical work

#38

**Comment by JJ** [comment]
1. This is not really a user story. This is context for a user story. The user story must have relationship to the business logic and represent a problem for an user, a problem you want to solve. "Requesting book information" is not a problem.
2. This is certainly not closed, since the user interface is not finished, and is not part of the milestone.

Actions: make it a simple issue, reopen it.
