### ISSUE TITLE
Milestone 1 is not really closed

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#92]
[This milestone](https://github.com/Anglepi/My-Many-Reads/milestone/2) is still missing one of the most important parts:

> From a list of books, provide recommendations of books not included in it.

Not entirely clear either if the first one is done 

> From an existing set of books, build a list of books.

Or even what kind of user story that would be. In general, users will add books one by one. Unless you want to provide facilities for importing list of read books from other application or program, in which case you should try and check what kind of formats are available for that kind of thing.

**Comment by Anglepi** [comment]
First point is the automatic recommendations functionality, which is already implemented but there is no API point at the moment. (first milestone did not require an active API nor referenced any specific way of accessing the functionality)

Second point refers to the creation of libraries but that is poorly explained in the milestone description 😅 .

Anyway, looking back at this I know the planification was not perfect and could have been done better, increasing the focus and importance of some functionalities rather than others, so the MVP developed for each milestone could provide more value for possible customers. I'm totally aware of the situation and I'm happy to say that I've learnt from this, but I don't think there's anything I can do to fix it now but to have in mind these flaws and attempt my best to not repeat them.
