### ISSUE TITLE
What is the source for books?

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#95]
It's not clear, in an user story or otherwise, what will be the source for book content. It's not very user friendly if users has to input all data by themselves, but if they do so, #94 has to be taken into consideration, plus some kind of validation should be included (beyond checking for correctness of ISBN).
You would need to explore ISBN APIs to check this kind of thing, probably.

**Comment by Anglepi** [comment]
During the next days I'm planning on preparing a script that imports books from any open dataset. I've been taking a look at [openlibrary](https://openlibrary.org/) where it seems I can download their books database but I haven't explored it yet. There are also some datasets available at [kaggle](https://www.kaggle.com/), but it is focused in data science instead of actual usage, so that might not be the best solution.

I will definitely try to get this done by the deadline, this and the improvements related to the recommendations system is my priority
